kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "spire-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spire-agent.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - "pods"
  - "nodes"
  - "nodes/proxy"
  verbs:
  - "get"
