apiVersion: v1
kind: ConfigMap
metadata:
  name: spire-agent
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spire-agent.labels" . | nindent 4 }}
data:
  agent.conf: |
    {{- tpl .Values.config . | nindent 4 }}
