apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spire-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spire-agent.labels" . | nindent 4 }}
data:
  agent.conf: |
    {{- include "spire-agent.conf" . | nindent 4 }}
