apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "spire-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spire-agent.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "spire-agent.selector-labels" . | nindent 6 }}
  template:
    metadata:
      namespace: {{ .Release.Namespace }}
      labels:
        {{- include "spire-agent.labels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: spire-agent
      initContainers:
        - name: init
          image: gcr.io/spiffe-io/wait-for-it
          args:
          - "-t"
          - "30"
          - "spire-server:8081"
      containers:
        - name: spire-agent
          image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
          args:
          - "-config"
          - "/run/spire/config/agent.conf"
          volumeMounts:
            - name: config
              mountPath: /run/spire/config
              readOnly: true
            - name: bootstrap
              mountPath: /run/spire/bootstrap
              readOnly: true
            - name: sockets
              mountPath: /run/spire/sockets
              readOnly: false
            - name: data
              mountPath: /run/spire/data
              readOnly: false
            - name: tokens
              mountPath: /var/run/secrets/tokens
          livenessProbe:
            httpGet:
              path: /live
              port: 8080
            failureThreshold: 2
            initialDelaySeconds: 15
            periodSeconds: 60
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: config
          configMap:
            name: {{ include "spire-agent.fullname" . }}
        - name: bootstrap
          configMap:
            name: trust-bundle
        - name: sockets
          hostPath:
            path: /run/spire/sockets
            type: DirectoryOrCreate
        - name: data
          emptyDir: {}
        - name: tokens
          projected:
            sources:
            - serviceAccountToken:
                path: spire-agent
                expirationSeconds: 7200
                audience: spire-server
