nameOverride: ""
fullnameOverride: ""

image:
  registry: "gcr.io"
  repository: "spiffe-io/spire-server"
  tag: "1.0.0"

config:
  bind:
    address: "0.0.0.0"
    port: 8081
  ca:
    keyType: "ec-p256"
    subject:
      country: ""
      organization: ""
      commonName: ""
    ttl: "24h"
  log:
    level: "INFO"
    format: "json"
  trustDomain: ""
  plugins:
    dataStore:
      sql:
        enabled: true
        databaseType: "sqlite3"
        connectionString: "/run/spire/data/dataStore.sqlite3"
    keyManager:
      disk:
        enabled: true
    nodeAttestor:
      k8sPsat:
        enabled: true
        cluster: ""
        serviceAccountAllowList: "spire:spire-agent"
    nodeResolver: {}
    upstreamAuthority:
      disk:
        enabled: true
    notifier:
      k8sbundle:
        enabled: true
  healthChecks:
    enabled: true
    bind:
      address: "0.0.0.0"
      port: 8080
    livePath: "/live"
    readyPath: "/ready"

persistence:
  enabled: true
  size: "1Gi"

service:
  type: ClusterIP