nameOverride: ""
fullnameOverride: ""

image:
  registry: "gcr.io"
  repository: "spiffe-io/spire-server"
  tag: "1.0.0"

config: |
  server {
    bind_address = "0.0.0.0"
    bind_port = {{ .Values.service.port | quote }}
    ca_key_type = "ec-p256"
    ca_subject = {
      country = ["US"],
      organization = ["SPIFFE"],
      common_name = "SPIRE",
    }
    ca_ttl = "24h"
    data_dir = "/run/spire/data"
    default_svid_ttl = "1h"
    log_level = "DEBUG"
    log_format = "json"
    socket_path = "/run/spire/sockets/api.sock"
    trust_domain = "example.org"
  }

  plugins {
    DataStore "sql" {
      plugin_data {
        database_type = "sqlite3"
        connection_string = "/run/spire/data/datastore.sqlite3"
      }
    }

    NodeAttestor "k8s_psat" {
      plugin_data {
        clusters = {
          "demo-cluster" = {
            service_account_allow_list = ["spire:spire-agent"]
          }
        }
      }
    }

    KeyManager "disk" {
      plugin_data {
        keys_path = "/run/spire/data/keys.json"
      }
    }

    UpstreamAuthority "disk" {
      plugin_data {
        key_file_path = "/run/spire/bootstrap/tls.key"
        cert_file_path = "/run/spire/bootstrap/tls.crt"
      }
    }

    Notifier "k8sbundle" {
      plugin_data {
        config_map = "trust-bundle"
        config_map_key = "trust-bundle.crt"
      }
    }
  }

  health_checks {
    listener_enabled = true
    bind_address = "0.0.0.0"
    bind_port = "8080"
    live_path = "/live"
    ready_path = "/ready"
  }

persistence:
  enabled: true
  size: "1Gi"

service:
  type: ClusterIP
  port: 8081