apiVersion: v1
kind: Service
metadata:
  name: {{ include "spire-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spire-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: grpc
      port: {{ .Values.config.bind.port }}
      targetPort: {{ .Values.config.bind.port }}
      protocol: TCP
  selector:
    {{- include "spire-server.selector-labels" . | nindent 4 }}
