apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "spire-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spire-server.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "spire-server.selector-labels" . | nindent 6 }}
  serviceName: {{ include "spire-server.fullname" . }}
  template:
    metadata:
      namespace: {{ .Release.Namespace }}
      labels:
        {{- include "spire-server.labels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ include "spire-server.fullname" . }}
      containers:
        - name: spire-server
          image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
          args:
            - "-config"
            - "/run/spire/config/server.conf"
          ports:
            - containerPort: {{ .Values.config.bind.port }}
          volumeMounts:
            - name: config
              mountPath: /run/spire/config
              readOnly: true
            - name: bootstrap
              mountPath: /run/spire/bootstrap
              readOnly: true
            - name: sockets
              mountPath: /run/spire/sockets
              readOnly: false
            - name: data
              mountPath: /run/spire/data
              readOnly: false
          {{- if .Values.config.healthChecks.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.config.healthChecks.livePath | quote }}
              port: {{ .Values.config.healthChecks.bind.port }}
            failureThreshold: 2
            initialDelaySeconds: 15
            periodSeconds: 60
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: {{ .Values.config.healthChecks.readyPath | quote }}
              port: {{ .Values.config.healthChecks.bind.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "spire-server.fullname" . }}
        - name: bootstrap
          secret:
            secretName: bootstrap-secret
        - name: sockets
          hostPath:
            path: /run/spire/sockets
            type: DirectoryOrCreate
  volumeClaimTemplates:
    - metadata:
        name: data
        namespace: {{ .Release.Namespace }}
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
